name: ci
on:
  push:
on:
  pull_request_target:
    types: [opened, closed]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install libusb, libudev (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libudev-dev

      - uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.3.0
        
      - name: Build
        run: |
          cargo build teleprobe
          cargo build teleprobe --release
          cargo test teleprobe
          cargo test teleprobe --release
    